# Generated by Django 5.0.3 on 2024-03-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='background',
            field=models.ImageField(default=1, upload_to='banner', verbose_name='Background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_text',
            field=models.TextField(default=1, verbose_name='Banner text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(default=1, max_length=25, verbose_name='Banner_title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='main_image',
            field=models.ImageField(default=1, upload_to='main_image', verbose_name='Main image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='mini_description',
            field=models.TextField(default=1, verbose_name='Mini description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='post_description',
            field=models.TextField(default=1, verbose_name='Post description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='quote',
            field=models.TextField(default=1, verbose_name='Quote'),
            preserve_default=False,
        ),
    ]
