# Generated by Django 5.0.3 on 2024-03-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_banner_image_remove_banner_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_1',
            field=models.ImageField(default=1, upload_to='image_1', verbose_name='Image 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_2',
            field=models.ImageField(default=1, upload_to='image_2', verbose_name='Image 2'),
            preserve_default=False,
        ),
    ]
