# Generated by Django 5.0.3 on 2024-03-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='news_banner', verbose_name='Banner image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='reservation_image',
            field=models.ImageField(default=1, upload_to='news_reservation', verbose_name='Reservation image'),
            preserve_default=False,
        ),
    ]
