# Generated by Django 5.0.3 on 2024-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_news_image_news_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='reservation_image',
        ),
        migrations.AlterField(
            model_name='news',
            name='banner_image',
            field=models.ImageField(upload_to='news', verbose_name='Image'),
        ),
    ]
