# Generated by Django 5.0.3 on 2024-03-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_news_reservation_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='banner_image',
            new_name='image',
        ),
    ]
