# Generated by Django 5.0.3 on 2024-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_banner_image_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('youtube', models.URLField(verbose_name='YouTube')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
    ]
