# Generated by Django 5.0.3 on 2024-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='background',
            field=models.ImageField(default=1, upload_to='back_about_us', verbose_name='Background'),
            preserve_default=False,
        ),
    ]
