# Generated by Django 5.0.3 on 2024-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_contactpost_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer', verbose_name='Image')),
                ('mini_description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Footer Info',
                'verbose_name_plural': 'Footer Infos',
            },
        ),
    ]
