# Generated by Django 5.0.3 on 2024-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Fullname')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('date', models.DateField(verbose_name='Date')),
                ('adults_quantity', models.IntegerField(verbose_name='Quantity of adults')),
                ('childs_quantity', models.IntegerField(verbose_name='Quantity of children')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
