# Generated by Django 5.0.3 on 2024-03-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_footerpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerpost',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
