# Generated by Django 5.0.3 on 2024-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_footerpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpost',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Date'),
        ),
    ]
