# Generated by Django 5.0.3 on 2024-03-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('video_name', models.CharField(max_length=255, verbose_name='Название видео')),
                ('video', models.URLField(verbose_name='URL Видео ')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга 2', 'verbose_name_plural': 'Услуги 2'},
        ),
    ]
