# Generated by Django 5.0.3 on 2024-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_video_alter_services_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='youtube',
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(default=1, verbose_name='URL twitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(default=1, verbose_name='URL facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team_image/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(default=1, verbose_name='URL instagram'),
            preserve_default=False,
        ),
    ]
